name: soil_mate
description: For collecting soil information at locations.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.7+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  hive: ^1.4.4
  path_provider: ^1.6.27
  hive_flutter: ^0.3.1
  flutter_mailer: ^1.0.1
  csv: ^4.1.0
  url_launcher: ^5.7.10
  geolocator: ^6.1.14
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon_ios.png"
  image_path_android: "assets/launcher/icon_ios.png"
  adaptive_icon_background: "assets/launcher/icon_android_back.png"
  adaptive_icon_foreground: "assets/launcher/icon_android_fore.png"

#run
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/car_icon.png
    - assets/credits_selfie.jpg
    - assets/discord_logo.jpg
    - assets/patreon_logo.png
    - assets/github_logo.png
    - assets/website_logo.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
